worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 127.0.0.1:80;
        server_name  localhost;

        # 测试 location，访问 http://127.0.0.1:8080/config 将返回本 location 的配置内容
        location /config {
            # 字符串
            my_str "hello config test";

            # 整数
            my_num 42;

            # 开关 on/off
            my_flag on;

            # 大小，支持 k/m 单位
            my_size 64k;

            # 字符串数组（1 或多个）
            my_array one two three;

            # key=val 列表
            my_keyval key1=value1 key2=value2;

            # 毫秒
            my_msec 1500ms;

            # 秒
            my_sec 3600;

            # 偏移量/长度
            my_off 12345;

            # 枚举（可选： one|two|three）
            my_enum_seq two;

            # self define config
            self_config 123 1;

            # 启用 dump handler，在访问该 location 时输出解析后的配置
            config_test_dump;
        }
    }
}
